# app
spring.application.name=loan-process-service
loan.max-age=70

# database
spring.datasource.url=jdbc:postgresql://localhost:5433/appdb
spring.datasource.username=appuser
spring.datasource.password=apppass

# liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:changelog/changelog-master.yml

# JPA
spring.jpa.hibernate.ddl-auto=validate